### ISSUE TITLE
[Bug] RSS feed 링크가 잘못되었습니다.

### ISSUE THREAD

**Issue by ysm-dev** [y0c/y0c.github.io#1]
![image](https://user-images.githubusercontent.com/18487241/60398688-1c144180-9b96-11e9-9540-ed18b5339c1f.png)

RSS링크를 누르면 `/atom.xml`로 가지는데 실제 RSS feed 주소는 `/feed.xml` 입니다.

개발브랜치는 푸쉬를 안하신거같아서 이슈로남깁니다. :)

**Comment by y0c** [comment]
@ysm0622 이슈로 남겨주셔서 감사합니다! 수정해서 다시 배포했습니다 🙂
